name: 'Setup google-java-format'
description: 'Sets up google-java-format for usage within your jobs.'
author: 'thecanadianroot'

inputs:
  token:
    description: 'The Github token.'
    default: ${{ github.token }}
  install-path:
    description: 'The install path for google-java-format. (defaults to current directory).'
    default: ${{ github.workspace }}
  version:
    description: 'The google-java-format version. (defaults to latest).'
    required: true
    default: 'latest'
  ignore-cached-install:
    description: 'Ignore cached install and install anyway? (defaults to false).'
    required: false
    default: 'false'

outputs:
  path:
    description: 'The install path of google-java-format.'
  version:
    description: 'The installed version of google-java-format.'

runs:
  using: node20
  main: dist/index.js
